// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
// ─── modules/webhooks/webhook.routes.ts — Payment Webhook Handler
// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════\n//
// PURPOSE:\n//   Receives payment confirmations from Dodo Payments\n//   No authentication (webhooks can't send JWT token)\n//   Instead: HMAC signature verification (Dodo secret)\n//
// ROUTE MAP (mounted at /webhooks):\n//   POST /dodo — Dodo Payments webhook (subscription & payment events)\n//
// WEBHOOK EVENTS:\n//\n//   subscription.update:\n//     • User completed checkout at POST /api/checkout/init\n//     • Dodo charged subscription fee\n//     • User upgraded from free → pro plan\n//     • Server updates: user.plan = \"pro\"\n//\n//   payment.complete:\n//     • User completed checkout at POST /api/checkout/topup\n//     • Dodo charged for credit top-up\n//     • Server updates: user.topup_credits += amount\n//\n//   subscription.cancel:\n//     • User clicked POST /api/subscription/cancel\n//     • Dodo marked subscription as canceled\n//     • At end of cycle: user.plan = \"free\"\n//\n//   payment.failed:\n//     • Dodo attempted to charge but failed (card expired, NSF, etc.)\n//     • No state change (user keeps current plan)\n//     • Server logs for debugging\n//\n// WEBHOOK FLOW:\n//   \n//   1. User completes payment in Dodo (e.g., purchases pro plan)\n//   2. Dodo calls POST /webhooks/dodo with:\n//      {\n//        \"eventId\": \"dodo_evt_123\",\n//        \"event_type\": \"subscription.update\",\n//        \"user_id\": \"dodo_user_456\",\n//        \"subscription_id\": \"sub_789\",\n//        \"plan\": \"pro\",\n//        \"timestamp\": \"2024-01-15T12:34:56Z\",\n//        \"signature\": \"hmac_signature_here\"\n//      }\n//   \n//   3. webhook.controller.ts dodoWebhookHandler receives request\n//   \n//   4. Step 1: Verify HMAC signature\n//      • Extract signature from request (header or body)\n//      • Reconstruct HMAC with DODO_WEBHOOK_SECRET\n//      • Compare: if mismatch, throw 403 Forbidden\n//      • Prevents attackers from faking webhooks\n//   \n//   5. Step 2: Check idempotency\n//      • Call markEventProcessed(eventId)\n//      • If return false → already processed, return 200 OK\n//      • If return true → proceed with processing\n//   \n//   6. Step 3: Process business logic\n//      • Extract event_type from request\n//      • subscription.update → user.plan = \"pro\", save to DB\n//      • payment.complete → user.topup_credits += amount, save to DB\n//      • payment.failed → log to logger, no DB change\n//   \n//   7. Step 4: Mark as completed\n//      • Call completeEventProcessed(eventId)\n//      • Updates status from 'processing' → 'completed'\n//      • Prevents re-processing even if Dodo retries\n//   \n//   8. Return 200 OK\n//      • Dodo receives 200 → assumes delivery successful\n//      • Dodo stops retrying\n//      • If we returned 500 → Dodo would retry for 7 days\n//
// IDEMPOTENCY (why important):\n//   \n//   Scenario: User completes checkout, server processes webhook successfully\n//   But network hiccup: Dodo doesn't receive our 200 OK response\n//   Dodo thinks: \"Server didn't acknowledge, must have failed\"\n//   Dodo retries webhook after 1 minute\n//   \n//   Without idempotency:\n//     • Webhook processed twice\n//     • User charged twice for same purchase\n//     • Angry customer → support ticket → refund effort\n//   \n//   With idempotency (this file):\n//     • First webhook: eventId doesn't exist → process, insert, status='processing'\n//     • Webhook processing completes: status='completed'\n//     • Dodo retries with same eventId\n//     • Second webhook: eventId exists, status='completed' → skip processing, return 200\n//     • User charged exactly once ✓\n//   \n//   This is handled by utils/idempotency.ts (see that file for full details)\n//
// NO AUTH REQUIRED:\n//   \n//   Why no Firebase JWT?\n//     • Webhook is server-to-server communication\n//     • Dodo server can't get Firebase token (no plugin context)\n//     • Instead: use Dodo as source of truth (Dodo API signed the request)\n//   \n//   Security via signature:\n//     • Only Dodo knows DODO_WEBHOOK_SECRET (stored in env)\n//     • Only Dodo can generate valid HMAC signature\n//     • Even if attacker knows endpoint URL, can't forge signature\n//     • Therefore: signature verification = authentication\n//
// WEBHOOK RETRY LOGIC (Dodo's behavior):\n//   \n//   If server returns 200 OK:\n//     • Dodo marks event as delivered\n//     • Stops retrying\n//   \n//   If server returns 5xx (500, 502, 503):\n//     • Dodo assumes server down\n//     • Retries exponentially: 1 min, 5 min, 30 min, 2 hours, 24 hours, etc.\n//     • Retries for ~7 days total\n//     • Each retry includes same eventId (idempotent)\n//   \n//   If server returns 4xx (400, 401, 403, 404):\n//     • Dodo assumes client error (webhook invalid, endpoint removed, etc.)\n//     • Stops retrying immediately\n//     • Logs error for manual investigation\n//   \n//   For this endpoint:\n//     • 200 OK if signature valid + processed\n//     • 403 Forbidden if signature invalid (stop retrying, investigate)\n//     • 500 Internal if database error (retry later)\n//
// REQUEST/RESPONSE EXAMPLES:\n//   \n//   POST /webhooks/dodo\n//   Headers:\n//     Content-Type: application/json\n//     X-Dodo-Signature: sha256=abc123...  (HMAC signature)\n//   \n//   Request body:\n//     {\n//       \"eventId\": \"dodo_evt_abc123xyz\",\n//       \"event_type\": \"subscription.update\",\n//       \"user_id\": \"dodo_user_456\",\n//       \"subscription_id\": \"sub_789\",\n//       \"plan\": \"pro\",\n//       \"amount_usd\": 19.99,\n//       \"billing_cycle_start\": \"2024-01-15T00:00:00Z\",\n//       \"billing_cycle_end\": \"2024-02-15T00:00:00Z\",\n//       \"timestamp\": \"2024-01-15T12:34:56Z\"\n//     }\n//   \n//   Response (200 OK):\n//     {\n//       \"success\": true,\n//       \"message\": \"Webhook processed\",\n//       \"eventId\": \"dodo_evt_abc123xyz\"\n//     }\n//   \n//   ---\n//   \n//   POST /webhooks/dodo (duplicate)\n//   Same request as above, but Dodo is retrying (network hiccup)\n//   \n//   Response (200 OK) — idempotent!\n//     {\n//       \"success\": true,\n//       \"message\": \"Webhook already processed\",\n//       \"eventId\": \"dodo_evt_abc123xyz\"\n//     }\n//   \n//   ---\n//   \n//   POST /webhooks/dodo (invalid signature)\n//   Headers:\n//     X-Dodo-Signature: sha256=wrong_signature_here\n//   \n//   Response (403 Forbidden):\n//     {\n//       \"error\": \"forbidden\",\n//       \"message\": \"Invalid webhook signature\"\n//     }\n//
// FIXES APPLIED:\n//   \n//   Fix SEC-C-01: Webhook signature validation\n//     • Validates DODO_WEBHOOK_SECRET at startup (startup.validation.ts)\n//     • Verifies every webhook request (webhook.controller.ts)\n//     • Prevents attackers from faking payment confirmations\n//   \n//   Fix NEW-I-03: Webhook idempotency\n//     • Marks event as processing before business logic\n//     • Completes event after logic succeeds\n//     • Prevents double-charging on Dodo retries\n//
// DATABASE COLLECTIONS MODIFIED:\n//   \n//   processed_webhooks (idempotency):\n//     • Insert { eventId, status: 'processing' }\n//     • Update status to 'completed' after processing\n//     • Checked on retry: if status='completed', skip re-processing\n//   \n//   users (plan state):\n//     • subscription.update: user.plan = 'pro', user.subscription_id = sub_id\n//     • payment.complete: user.topup_credits += amount\n//     • payment.failed: no change, just log\n//
// LOGGING:\n//   \n//   Every webhook request logged:\n//     • Request ID for correlation\n//     • User ID (extracted from webhook)\n//     • Event type\n//     • Signature verification result (valid/invalid)\n//     • Processing result (success/error)\n//   \n//   Examples:\n//     [req:uuid-123] webhook.controller dodoWebhookHandler: received subscription.update\n//     [req:uuid-123] webhook.controller dodoWebhookHandler: signature valid\n//     [req:uuid-123] webhook.controller dodoWebhookHandler: processing event\n//     [req:uuid-123] webhook.controller dodoWebhookHandler: updated user.plan to pro\n//     [req:uuid-123] webhook.controller dodoWebhookHandler: marked event completed\n//     [req:uuid-123] webhook.controller dodoWebhookHandler: responded 200 OK
//
// ERROR SCENARIOS:\n//   \n//   Signature invalid:\n//     • throw new ForbiddenError('Invalid webhook signature')\n//     • error.middleware catches, returns 403\n//     • Dodo stops retrying (recognizes client error)\n//   \n//   Database down:\n//     • markEventProcessed throws\n//     • webhook.controller catches, throws 500\n//     • error.middleware returns 500\n//     • Dodo retries after 1 minute (waits for recovery)\n//   \n//   User not found:\n//     • Rare (Dodo should only send webhooks for users we know)\n//     • Log error, still return 200 (can't fix via retry)\n//     • Manual investigation needed\n//   \n//   Event processing throws:\n//     • markEventFailed(eventId) called (mark as failed, safe for retry)\n//     • throw error\n//     • error.middleware returns 500\n//     • Dodo retries after 1 minute

import { Router, Request, Response, NextFunction } from 'express';
import { dodoWebhookHandler } from './webhook.controller';

const router = Router();

router.post(
  '/dodo',
  (req: Request & { rawBody?: Buffer }, res: Response, next: NextFunction) => {
    dodoWebhookHandler(req, res).catch(next);
  }
);

export default router;
