// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
// ─── modules/payments/payment.types.ts — Payment & Checkout Types
// ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
//
// PURPOSE:\n//   TypeScript interfaces for payment checkout flows\n//   Covers: plan upgrade checkout, credit top-up checkout, Dodo integration\n//\n// CHECKOUT TYPES:\n//   \n//   InitCheckoutRequest:\n//     • Client request to POST /api/checkout/init\n//     • User wants to upgrade from free → pro plan\n//   \n//   TopUpCheckoutRequest:\n//     • Client request to POST /api/checkout/topup\n//     • User wants to buy additional credits (pro only)\n//   \n//   CheckoutResponse:\n//     • Server response from both endpoints\n//     • Contains Dodo checkout URL for client redirect\n//
// INIT CHECKOUT (Plan Upgrade - Trigger C):\n//   \n//   InitCheckoutRequest:\n//     • planId (PlanId: 'free' | 'pro', optional)\n//       • Which plan to upgrade to\n//       • If omitted: defaults to 'pro' (only option)\n//       • 'free': no-op (user already free, nothing to upgrade)\n//       • 'pro': standard checkout (redirect to Dodo)\n//   \n//   Workflow:\n//     1. Free user sees \"Upgrade to Pro\" button in plugin\n//     2. User clicks → POST /api/checkout/init { planId: 'pro' }\n//     3. Server calls dodoProvider.createPlanCheckout(userId, 'pro')\n//     4. Dodo API returns: { checkout_url, checkout_id, expires_in: 1800 }\n//     5. Server returns: CheckoutResponse to client\n//     6. Client's JavaScript: window.location.href = checkoutUrl\n//     7. Browser redirects to Dodo checkout page\n//     8. User enters credit card info in Dodo (secure, hosted by Dodo)\n//     9. User clicks \"Pay now\"\n//     10. Dodo processes payment\n//     11. If successful: Dodo calls POST /webhooks/dodo { event_type: 'subscription.update' }\n//     12. Server updates: user.plan = 'pro'\n//     13. Browser redirects back to plugin (success page)\n//     14. User now has pro plan and can use premium features\n//   \n//   CheckoutResponse for /init:\n//     {\n//       \"checkoutUrl\": \"https://checkout.dodo.com/session/sess_123...\",\n//       \"checkoutId\": \"sess_123\",\n//       \"pack_info\": undefined  // Not used for plan upgrades\n//     }\n//   \n//   Error cases:\n//     • User already pro → 409 Conflict (\"Already on pro plan\")\n//     • Dodo API down → 502 Bad Gateway (\"Checkout service unavailable\")\n//     • Checkout rate limit exceeded → 429 Too Many Requests\n//
// TOP-UP CHECKOUT (Credit Purchase - Trigger D):\n//   \n//   TopUpCheckoutRequest:\n//     • packId (TopUpPackId: '100' | '500' | '1000', optional)\n//       • Which credit package to buy\n//       • '100': 100 credits for $2.99\n//       • '500': 500 credits for $9.99 (save 25%)\n//       • '1000': 1000 credits for $19.99 (save 33%)\n//       • If omitted: defaults to '500'\n//     • Must be pro user (requireProMiddleware enforces)\n//   \n//   Workflow:\n//     1. Pro user has low credits (e.g., 50 left)\n//     2. User clicks \"Buy More Credits\" in plugin\n//     3. Plugin shows 3 options: 100/$2.99, 500/$9.99, 1000/$19.99\n//     4. User selects 500 credits\n//     5. User clicks → POST /api/checkout/topup { packId: '500' }\n//     6. Server calls dodoProvider.createTopUpCheckout(userId, packId='500')\n//     7. Dodo API returns: { checkout_url, checkout_id }\n//     8. Server returns: CheckoutResponse to client\n//     9. Client redirects to Dodo checkout\n//     10. User pays $9.99 (user's card stored in Dodo)\n//     11. Dodo calls POST /webhooks/dodo { event_type: 'payment.complete', credits: 500 }\n//     12. Server updates: user.topup_credits += 500\n//     13. Browser redirects back to plugin\n//     14. User can generate again (new credit balance: 550)\n//   \n//   CheckoutResponse for /topup:\n//     {\n//       \"checkoutUrl\": \"https://checkout.dodo.com/session/sess_456...\",\n//       \"checkoutId\": \"sess_456\",\n//       \"pack_info\": {\n//         \"credits\": 500,\n//         \"price\": \"$9.99\"\n//       }\n//     }\n//   \n//   Error cases:\n//     • User not pro → 403 Forbidden (\"Only pro users can top-up\")\n//     • Invalid packId → 400 Bad Request (\"Pack must be 100, 500, or 1000\")\n//     • Dodo API down → 502 Bad Gateway\n//     • Checkout rate limit exceeded → 429 Too Many Requests\n//
// DODO PAYMENTS INTEGRATION:\n//   \n//   Dodo is external payment provider (not our system):\n//     • Hosted checkout page (user enters card in Dodo's domain)\n//     • PCI-DSS compliant (we don't handle credit card data)\n//     • Subscription management (Dodo handles recurring billing)\n//     • Webhook notifications (Dodo calls us when payment succeeds)\n//   \n//   Why Dodo instead of Stripe/Square?\n//     • Dodo supports subscription auto-billing (monthly)\n//     • Dodo has good regional coverage (supports many countries)\n//     • Dodo has lower payment fees for SaaS (2.5% + $0.30)\n//   \n//   Checkout URL format:\n//     • https://checkout.dodo.com/session/{checkout_id}\n//     • Unique per request (prevents replay attacks)\n//     • Expires after 30 minutes (client must complete payment within 30 min)\n//     • After payment: Dodo redirects to success_url (configured in Dodo dashboard)\n//   \n//   Error handling:\n//     • If Dodo API unavailable: we return 502, client sees error\n//     • If user abandons checkout: checkout session expires, user can start over\n//     • If payment fails: Dodo shows error page, user can retry\n//     • If webhook fails to reach us: Dodo retries for 7 days (idempotent)\n//
// WEBHOOK CONFIRMATION:\n//   \n//   After user completes Dodo checkout:\n//   \n//   subscription.update (plan upgrade):\n//     • Dodo sends: { event_type: 'subscription.update', user_id, subscription_id, plan: 'pro' }\n//     • Server: marks user as pro, stores dodo_subscription_id\n//     • User now has pro features: higher credits, no rate limits\n//   \n//   payment.complete (topup):\n//     • Dodo sends: { event_type: 'payment.complete', user_id, credits: 500 }\n//     • Server: adds credits to user.topup_credits\n//     • User can generate again\n//   \n//   payment.failed:\n//     • Dodo sends: { event_type: 'payment.failed', user_id, error_code, card_last4 }\n//     • Server: logs error, no plan change\n//     • User's subscription/credits unchanged (still have old plan)\n//     • Dodo retries auto-billing for ~7 days\n//
// PRICING CONFIGURATION:\n//   \n//   In constants.ts:\n//     • TOPUP_PACKS = [\n//         { id: '100', credits: 100, price_usd: 2.99 },\n//         { id: '500', credits: 500, price_usd: 9.99 },\n//         { id: '1000', credits: 1000, price_usd: 19.99 }\n//       ]\n//     • PLAN_CONFIG.pro.monthly_credits = 500000 (plan credits per month)\n//     • PLAN_CONFIG.pro.subscription_price_usd = 19.99 (monthly subscription fee)\n//   \n//   In Dodo dashboard:\n//     • Plan upgrade product: $19.99/month recurring\n//     • Topup 100 credits: $2.99 one-time\n//     • Topup 500 credits: $9.99 one-time\n//     • Topup 1000 credits: $19.99 one-time\n//   \n//   Pricing must match (constants.ts = Dodo products)\n//   If mismatch: user charged wrong amount, trust issues\n//   Solution: no manual price in response, fetch from Dodo\n//
// CHECKOUT RATE LIMIT:\n//   \n//   Max 15 checkouts per 60 seconds per user (Fix NEW-H-02)\n//   Prevents: accidental double-clicks, spam/abuse\n//   Stored in: checkout_rate_limits collection (TTL=120s)\n//   Returns: 429 Too Many Requests if exceeded\n//
// EXAMPLE FLOW (complete topup journey):\n//   \n//   1. User has 30 topup credits left, wants to generate\n//   2. User clicks \"Generate\" button\n//   3. POST /api/features/generate/start\n//      → Reserves 5 credits (from 30, now 25)\n//      → Budget check passes\n//      → Streaming generation starts\n//   4. Generation completes in 2 minutes\n//   5. After stream: actual cost = 4.8 credits (rounded to 5)\n//      → User now has 25 topup credits\n//   6. User realizes: \"I'll run out soon, better buy more\"\n//   7. User clicks \"Buy More Credits\" button in plugin\n//   8. Plugin shows: \"100 credits for $2.99, 500 for $9.99, 1000 for $19.99\"\n//   9. User selects 500 credits (best value)\n//   10. POST /api/checkout/topup { packId: '500' }\n//       → dodoProvider.createTopUpCheckout(userId, '500')\n//       → Dodo creates checkout session\n//       → Returns: https://checkout.dodo.com/session/sess_abc123\n//   11. Server returns CheckoutResponse:\n//       {\n//         checkoutUrl: \"https://checkout.dodo.com/session/sess_abc123\",\n//         checkoutId: \"sess_abc123\",\n//         pack_info: { credits: 500, price: \"$9.99\" }\n//       }\n//   12. Client receives response, JavaScript redirects:\n//       window.location.href = checkoutUrl\n//   13. Browser navigates to Dodo checkout page\n//   14. Dodo checkout shows: \"$9.99 for 500 credits\"\n//   15. User enters credit card (or uses saved card from previous purchase)\n//   16. User clicks \"Pay now\"\n//   17. Dodo processes payment (2-3 seconds)\n//   18. If successful: Dodo calls POST /webhooks/dodo\n//       {\n//         eventId: \"dodo_evt_xyz789\",\n//         event_type: \"payment.complete\",\n//         user_id: \"dodo_user_123\",\n//         credits: 500\n//       }\n//   19. webhook.controller processes:\n//       • Verifies signature (DODO_WEBHOOK_SECRET)\n//       • Checks idempotency (markEventProcessed)\n//       • Updates: user.topup_credits += 500 (now 525)\n//       • Marks event: completeEventProcessed\n//       • Returns: 200 OK\n//   20. Dodo receives 200 OK, stops retrying\n//   21. Dodo redirects browser back to plugin (success page)\n//   22. Plugin refreshes user state\n//   23. User sees: \"525 credits available!\"\n//   24. User can generate again\n//

import { PlanId, TopUpPackId } from '../../config/constants';

export interface InitCheckoutRequest {
  planId?: PlanId;
}

export interface TopUpCheckoutRequest {
  packId?: TopUpPackId;
}

export interface CheckoutResponse {
  checkoutUrl: string;
  checkoutId: string;
  pack_info?: {
    credits: number;
    price: string;
  };
}
